### ISSUE TITLE
Duvidas e considerações sobre esse guia.

### ISSUE THREAD

**Issue by siimaoo** [Hai-San/orcss#24]
Recentemente recebi esse styleguide e aqui vai algumas duvidas/considerações.

Logo na primeira [página](https://orcss.dev.br/guide/) tem algo escrito como "Bibliotecas de CSS-IN-JS (styled-components, emotion) => Só serve pra complicar." e ai vem a primeira duvida: 

### Complicar o que? Pq libs css-in-js complicam algo? 

Gigantes como spotify, digital ocean, codesandbox, quora, discord, trello, bitbucket, tiktok, binance todas usam ou styled components ou emotion, será mesmo que css puro seguindo um guide é melhor?

### Usar apenas tailwind ou alguma lib de componentes deixam os designers limitados?
Obviamente a resposta é não, você pode usar alguma lib de componentes (AntD) e usar o tailwind junto e construir o que a lib de componentes não te fornecer, e pasmem, usando o tailwind.

### É necessário que toda a equipe de desenvolvedores tenha domínio sobre a solução utilizada.
Essa afirmação não faz muito sentido, sendo que qualquer solução é necessário que toda a equipe tenha domínio, mesmo se escolhesse usar oq é descrito nesse guia, e digo mais, tailwind pelo menos tem extensão para vscode + plugins para eslint e prettier, o que esse guia não tem.

Também não faz sentido dizer que a curva de aprendizagem de utility first é alta, pq basicamente é só copiar e colocar uma classe, diferente de um paradigma, estilo de codigo ou linguagem de programação, e mais uma vez, o tailwind como exemplo tem diversas extensões para facilitar a sua utilização.

### Nesses casos pode funcionar bem no começo do negócio, mas no longo prazo pode ficar bem complicado
Gostaria de exemplos, pois é comum vermos diversas gigantes da tecnologia migrando para utility first + css in js, será mesmo se um enorme time de engenharia de diversas empresas estão errados em não utilizar css puro?

**Comment by Hai-San** [comment]
Fala @siimaoo, massa tu gerar esse discussão. Alias, desculpa pela demora em responder.
Bora lá.
Uma coisa que vi que tu comentou bastante foi que se as gigantes de tecnologia usam, então isso deve ser o certo. Se tem uma coisa que eu aprendi com o tempo é que tamanho e popularidade de empresa não significa nada, pois no fim todas são formadas por pessoas. Tá, e o que isso tem a ver com o assunto? Isso significa que todas as empresas estão propensas aos mesmos erros.

Vou responder suas questões baseadas nesse meu primeiro comentário.

### Complicar o que? Pq libs css-in-js complicam algo?
Pensa assim, o CSS é a base core de estilos, qualquer DEV tem que aprender CSS, principalmente fronts. O CSS-IN-JS não foi algo que surgiu com o objetivo de melhorar o CSS, ele foi algo que surgiu com o React apenas como forma de encaixar melhor o CSS no "estilo scriptado" do react. Eles trazem até alguns pontos sobre melhorar conflitos etc... Mas isso ai é a parte mais tranquila de se fazer com CSS puro.

### Usar apenas tailwind ou alguma lib de componentes deixam os designers limitados?
Aqui talvez eu devesse mudar a descrição ali na sobre, pois incluo tudo no mesmo pacote, mas cada coisa tem seus problema individual. O tailwind no caso muda toda forma de escrever CSS pra chegar no mesmo ponto que o CSS padrão executa de forma perfeita, ou seja, tu muda tudo pra nada e ainda corre o risco da biblioteca ser deixada de lado ou não ser atualizada tão frequentemente como deveria para acompanhar o crescimento do CSS. Bootstrap no caso limita os designers, pois tem estilos o formas próprias de componentes e isso exige que o designer estude a biblioteca.

### É necessário que toda a equipe de desenvolvedores tenha domínio sobre a solução utilizada.
Então, eu parto do ponto que todo front sabe CSS, e todo o resto das soluções de estilo são mais desconhecidas. O projeto é mais um guia pra auxiliar quem já conhece o CSS e quer aprender técnicas melhores pro CSS não ficar bagunçado e ruim de manter e parar de buscar "soluções" prontas, não sei se teria como criar uma extensão pra isso. Por isso no módulo de configurações eu indico algumas extensões pra ajudar nessa organização e manter um padrão legal. Isso é algo que exige uma maturidade dos DEVs da empresa sentarem juntos e cobrarem uns dos outros no seguimento das regras. Inclusive apensar do guia ser feito pensando no CSS puro tu consegue aplicar muita coisa para outros tipos de soluções.

### Nesses casos pode funcionar bem no começo do negócio, mas no longo prazo pode ficar bem complicado
Aqui meio que meu comentário lá no começo responde um pouco, mas parte do pressuposto que as gigantes não estão livres de erros e problemas. Eu acredito muito mais na durabilidade do CSS do que do tailwind que é algo criado sustentado por pessoas que não tem uma obrigação real de continuar evoluindo o projeto. Outro ponto é que eu nunca vi alguém usar só bootstrap ou só tailwind, sempre vira uma mistura de CSS puro + alguma solução e isso fica muito caótico no longo prazo.

Só pra concluir, isso é algo que tirei da minha experiencia e pode não dar certo para todas as pessoas, vai muito da linha de raciocínio de cada um. Eu por exemplo sou um front-end mais "styleiro" e normalmente quem é mais "scripteiro" não tem muita concordância com as coisas que eu penso. O Meu objetivo aqui é fazer a galera tira o proveito máximo do CSS e evitar ter que aprender uma nova forma de escrever CSS cada vez que entra em uma empresa diferente ou a cada seis meses kkkk CSS é pra ser algo simples.
